tasks:
  - name: Dev Server
    before: npm install && clear
    init: npm run dev -- -p 6500
    command: npm run dev -- -p 6500
  - name: Git
    init: git status -s

ports:
  - port: 6500
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - bradlc.vscode-tailwindcss
    - redhat.vscode-xml
    - dsznajder.es7-react-js-snippets
    - usernamehw.errorlens
    - formulahendry.auto-rename-tag
    - PKief.material-icon-theme
    - Equinusocio.vsc-material-theme
